export const FACE_RECOGNITION_INTERVAL_MS = 100;
export const FACE_ENROLLMENT_INTERVAL_MS = 250;
export const ENROLLMENT_SAMPLE_COUNT = 10;
export const FACE_DETECTION_MIN_CONFIDENCE = 0.5;
export const FACE_ENROLLMENT_MIN_WIDTH_RATIO = 0.2;
export const FACE_RECOGNITION_MIN_WIDTH_RATIO = 0.08;
export const FACE_MIN_INSIDE_RATIO = 0.7;

export const FACE_MATCH_THRESHOLD = 0.62;
export const FACE_MATCH_MARGIN = 0.08;
export const PREDICTION_WINDOW_SIZE = 5;
export const PREDICTION_REQUIRED_MATCHES = 4;
export const IDENTITY_SWITCH_REQUIRED_MATCHES = 5;
